In [1]:
# Select data and directories structure.
import os
import glob
import numpy as np
import pandas as pd
import nibabel as nib
from nibabel.testing import data_path
file = os.path.join(nib.testing.data_path, '/Users/julioyanes/Desktop/scratch/tmind.nii')
img = nib.load(file)
img.shape

(91, 109, 91)

In [2]:
# 3-deminsional array to 1-dimensional array.
img_array = np.asarray(np.ravel(img.get_data(), order='C').T)
print('features = {0}'.format(len(img_array)))
print(img_array)
print('max value = {0}'.format(np.amax(img_array)))

features = 902629
[0. 0. 0. ... 0. 0. 0.]
max value = 15.146350628850822


In [3]:
# Min/max scale array.
img_array_mms = np.asarray(img_array/np.amax(img_array))
print('features = {0}'.format(len(img_array_mms)))
print(img_array_mms)
print('max value = {0}'.format(np.amax(img_array_mms)))

features = 902629
[0. 0. 0. ... 0. 0. 0.]
max value = 1.0


In [4]:
# Transpose Array
img_array_mms_rs = img_array_mms[np.newaxis,:]
print('features = {0}'.format(len(img_array_mms_rs)))
print(img_array_mms_rs)
print('max value = {0}'.format(np.amax(img_array_mms_rs)))

features = 1
[[0. 0. 0. ... 0. 0. 0.]]
max value = 1.0


In [5]:
frame = pd.DataFrame(data=img_array_mms_rs)
frame.to_csv ('/Users/julioyanes/Desktop/scratch/out/tmind.csv')