In [14]:
# Select data and directories structure.
import os
import glob
import numpy as np
import pandas as pd
import nibabel as nib
from nibabel.testing import data_path
file = os.path.join(nib.testing.data_path, '/Users/julioyanes/Desktop/pain.nii.gz')
img = nib.load(file)
img.shape

(91, 109, 91, 1)

In [15]:
# 3-deminsional array to 1-dimensional array.
img_array_pain = np.asarray(np.ravel(img.get_data(), order='C').T)
print('features = {0}'.format(len(img_array_pain)))
print(img_array_pain)
print('max value = {0}'.format(np.amax(img_array_pain)))

features = 902629
[0. 0. 0. ... 0. 0. 0.]
max value = 978772.6875


In [16]:
# Min/max scale array.
img_array_pain_mms = np.asarray(img_array/np.amax(img_array_pain))
print('features = {0}'.format(len(img_array_pain_mms)))
print(img_array_pain_mms)
print('max value = {0}'.format(np.amax(img_array_pain_mms)))

features = 902629
[0. 0. 0. ... 0. 0. 0.]
max value = 1.0051732063293457


In [17]:
file = os.path.join(nib.testing.data_path, '/Users/julioyanes/Desktop/nopain.nii.gz')
img = nib.load(file)
img.shape
# 3-deminsional array to 1-dimensional array.
img_array_nopain = np.asarray(np.ravel(img.get_data(), order='C').T)
print('features = {0}'.format(len(img_array_nopain)))
print(img_array_nopain)
print('max value = {0}'.format(np.amax(img_array_nopain)))
# Min/max scale array.
img_array_nopain_mms = np.asarray(img_array/np.amax(img_array_nopain))
print('features = {0}'.format(len(img_array_nopain_mms)))
print(img_array_nopain_mms)
print('max value = {0}'.format(np.amax(img_array_nopain_mms)))

features = 902629
[0. 0. 0. ... 0. 0. 0.]
max value = 983499.625
features = 902629
[0. 0. 0. ... 0. 0. 0.]
max value = 1.0003421306610107


In [21]:
img_subtract = img_array_pain_mms - img_array_nopain_mms

In [ ]:
# Transpose Array
img_array_mms_rs = img_array_mms[np.newaxis,:]
print('features = {0}'.format(len(img_array_mms_rs)))
print(img_array_mms_rs)
print('max value = {0}'.format(np.amax(img_array_mms_rs)))

In [24]:
frame = pd.DataFrame(data=img_subtract)
frame.to_csv ('/Users/julioyanes/Dropbox/_Yanes/Github/metaclass/openneuro/subtract.csv')